<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
 
 use Phalcon\Forms\Element\Radio;
 use Phalcon\Forms\Element\Select;
?>


<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["users", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Add users
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "users/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">Lastname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Lastname", "size" => 30, "class" => "form-control", "id" => "fieldLastname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGender" class="col-sm-2 control-label">Gender</label>
    <div class="col-sm-10">
        <?php 	echo $yes = new Radio("Gender", array("id" => "myYes", "value" => 'M'));print("Male"); ?>
				
		<?php 	echo $no = new Radio("Gender", array("id" => "myNo", "value" => 'F'));print("Female"); ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldEducation" class="col-sm-2 control-label">Education</label>
    <div class="col-sm-10">
        <select id="Education" name="Education">
    <option value="BCA">BCA</option>
    <option value="BBA">BBA</option>
    <option value="MBA">MBA</option>
    <option value="MSc">MSc</option>
</select>
    </div>
</div>



<div class="form-group">
    <label for="fieldSkills" class="col-sm-2 control-label">Skills</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Skills", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSkills"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
